<?php
/**
 * Created by PhpStorm.
 *
 * kookaburra
 * (c) 2019 Craig Rayner <craig@craigrayner.com>
 *
 * User: craig
 * Date: 30/11/2019
 * Time: 18:09
 */

namespace Kookaburra\UserAdmin\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

class Configuration implements ConfigurationInterface
{
    /**
     * getConfigTreeBuilder
     * @return TreeBuilder
     */
    public function getConfigTreeBuilder()
    {
        $treeBuilder = new TreeBuilder('kookaburra_user_admin');
        $treeBuilder->getRootNode()
            ->children()
                ->arrayNode('name_formats')
                    ->children()
                        ->arrayNode('staff')
                            ->children()
                                ->arrayNode('first')
                                    ->children()
                                        ->arrayNode('short')
                                            ->children()
                                                ->scalarNode('reversed')->end()
                                                ->scalarNode('normal')->end()
                                            ->end()
                                        ->end()
                                        ->arrayNode('long')
                                            ->children()
                                                ->scalarNode('reversed')->end()
                                                ->scalarNode('normal')->end()
                                            ->end()
                                        ->end()
                                    ->end()
                                ->end()
                                ->arrayNode('preferred')
                                    ->children()
                                        ->arrayNode('short')
                                        ->children()
                                        ->scalarNode('reversed')->end()
                                        ->scalarNode('normal')->end()
                                        ->end()
                                        ->end()
                                        ->arrayNode('long')
                                        ->children()
                                        ->scalarNode('reversed')->end()
                                        ->scalarNode('normal')->end()
                                        ->end()
                                        ->end()
                                    ->end()
                                ->end()
                                ->scalarNode('formal')->end()
                            ->end()
                        ->end()
                        ->arrayNode('student')
                            ->children()
                                ->arrayNode('first')
                                    ->children()
                                        ->arrayNode('short')
                                            ->children()
                                                ->scalarNode('reversed')->end()
                                                ->scalarNode('normal')->end()
                                            ->end()
                                        ->end()
                                        ->arrayNode('long')
                                            ->children()
                                                ->scalarNode('reversed')->end()
                                                ->scalarNode('normal')->end()
                                            ->end()
                                        ->end()
                                    ->end()
                                ->end()
                                ->arrayNode('preferred')
                                    ->children()
                                        ->arrayNode('short')
                                            ->children()
                                                ->scalarNode('reversed')->end()
                                                ->scalarNode('normal')->end()
                                            ->end()
                                        ->end()
                                        ->arrayNode('long')
                                            ->children()
                                                ->scalarNode('reversed')->end()
                                                ->scalarNode('normal')->end()
                                            ->end()
                                        ->end()
                                    ->end()
                                ->end()
                                ->scalarNode('formal')->end()
                            ->end()
                        ->end()
                        ->arrayNode('parent')
                            ->children()
                                ->arrayNode('first')
                                    ->children()
                                        ->arrayNode('short')
                                            ->children()
                                                ->scalarNode('reversed')->end()
                                                ->scalarNode('normal')->end()
                                            ->end()
                                        ->end()
                                        ->arrayNode('long')
                                            ->children()
                                                ->scalarNode('reversed')->end()
                                                ->scalarNode('normal')->end()
                                            ->end()
                                        ->end()
                                    ->end()
                                ->end()
                                ->arrayNode('preferred')
                                    ->children()
                                        ->arrayNode('short')
                                            ->children()
                                                ->scalarNode('reversed')->end()
                                                ->scalarNode('normal')->end()
                                            ->end()
                                        ->end()
                                        ->arrayNode('long')
                                            ->children()
                                                ->scalarNode('reversed')->end()
                                                ->scalarNode('normal')->end()
                                            ->end()
                                        ->end()
                                    ->end()
                                ->end()
                                ->scalarNode('formal')->end()
                            ->end()
                        ->end()
                        ->arrayNode('other')
                            ->children()
                                ->arrayNode('first')
                                    ->children()
                                        ->arrayNode('short')
                                            ->children()
                                                ->scalarNode('reversed')->end()
                                                ->scalarNode('normal')->end()
                                            ->end()
                                        ->end()
                                        ->arrayNode('long')
                                            ->children()
                                                ->scalarNode('reversed')->end()
                                                ->scalarNode('normal')->end()
                                            ->end()
                                        ->end()
                                    ->end()
                                ->end()
                                ->arrayNode('preferred')
                                    ->children()
                                        ->arrayNode('short')
                                            ->children()
                                                ->scalarNode('reversed')->end()
                                                ->scalarNode('normal')->end()
                                            ->end()
                                        ->end()
                                        ->arrayNode('long')
                                            ->children()
                                                ->scalarNode('reversed')->end()
                                                ->scalarNode('normal')->end()
                                            ->end()
                                        ->end()
                                    ->end()
                                ->end()
                                ->scalarNode('formal')->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end()
        ;

        return $treeBuilder;
    }
}
